title: Meta
data:
  tagline:
    -
      type: paragraph
      content:
        -
          type: text
          text: 'Commercial and residential'
        -
          type: hardBreak
        -
          type: text
          text: 'plant design and landscaping'
  contact: 'For inquiries'
  email: hello@itoitocreative.com
  use_label: false
