tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: contact
            field:
              buttons:
                - anchor
              smart_typography: false
              save_html: false
              inline: false
              toolbar_mode: fixed
              reading_time: false
              word_count: false
              fullscreen: false
              allow_source: false
              enable_input_rules: false
              enable_paste_rules: false
              remove_empty_nodes: true
              antlers: false
              link_noopener: true
              link_noreferrer: true
              target_blank: true
              always_show_set_button: false
              collapse: false
              previews: true
              type: bard
              display: Contact
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: tagline
            field:
              smart_typography: false
              save_html: false
              inline: false
              toolbar_mode: fixed
              reading_time: false
              word_count: false
              fullscreen: true
              allow_source: true
              enable_input_rules: true
              enable_paste_rules: true
              remove_empty_nodes: trim
              antlers: false
              link_noopener: false
              link_noreferrer: false
              target_blank: false
              always_show_set_button: false
              collapse: false
              previews: true
              type: bard
              display: Tagline
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
